export  const SETTINGS_CREATE = 'SETTINGS_CREATE';
export  const DOMAIN_IGNORED_UPDATE = 'DOMAIN_IGNORED_UPDATE';
export  const DOMAIN_IGNORED_DELETE = 'DOMAIN_IGNORED_DELETE ';

export  const LIMITS_TEXT_CREATE = 'LIMITS_TEXT_CREATE';
export  const WEB_NAME_UPDATE = 'WEB_NAME_UPDATE';
export  const WEB_NAME_DELETE = 'WEB_NAME_DELETE';


export  const TIME_TEXT_CREATE = 'TIME_TEXT_CREATE';
export  const TIME_TEXT_UPDATE = 'TIME_TEXT_CREATE';
export  const TIME_TEXT_DELETE = 'TIME_TEXT_CREATE';